= Rescue mode

Rescue mode is useful for repairing some problems that prevent booting
and/or logging in.

NOTE: If your computer's Setup utility is locked with a password, you
may need that password to select booting from your installation media.

. Boot from installation media
. Select *Advanced options ...*
. Select *... Rescue mode*
. Select Language (*English*)
. Select country (*United States*)
. Select keymap (*American English*)
. Network configuration
+

TIP: If you don't use DHCP and experience a lengthy DHCP search, you
can press *Enter* to cancel it.

+

If you get a *Network autoconfiguration failed* message: press *Enter*
and continue with the next paragraph in this numbered step.  Otherwise
the DHCP configuration will have succeeded (you will prompted for a
        hostname), and (a) you do not want to use it as part of your
repair work: select *Go Back* and continue with the next paragraph in
this step; or (b) you want to use it as part of your repair work: set
your hostname and domain name appropriately when prompted, pressing
*Enter* for each, then proceed to the next numbered step below.

+

If you do not need the network: select *Do not configure the network
at this time*, when asked for the hostname, press *Enter*, then
proceed to the next numbered step below. Otherwise if you do need the
network: select the appropriate configuration method and respond to
the prompts as is suitable.

. Select time zone (*Eastern*)
. Select *Assemble RAID array*
. Press *Space* on *Automatic*
+
Use *Enter* to continue

. Select your root file system (*/dev/lv/root*)
. Select *Yes* to mount */boot*
. Select *Yes* to mount */boot/efi*
. Select *Execute a shell in /dev/lv/root* (i.e., in your root file system)
. Select *Continue* to enter rescue mode
. Use whatever commands are needed for your repair
. Use the *exit* command to exit when done
. Select *Reboot the system*
. *Bob's your uncle*

