= CIS hardening FSL10, take 2
Dave Horsley and Ed Himwich
Jan 2020

:experimental:
:toc:

== Introduction

These notes detail adding extra security features to Field System
Linux 10 as advised by Center for Internet Security (CIS). With the
exception of the partition configuration, all actions are to be
performed post-installation. All tests that failed, topics that need
to be discussed, and issues with the benchmark remediations are
provided in separate sections at the end of this document.

A useful minimum set of features to apply would be the `ufw` section
from the `remediate` script and to implement the `/etc/hosts.deny` and
`/etc/hosts.allow` policies given below.

This document  is based on the results for the CIS Debian Linux 9
Benchmark v1.0.0 - Level 2 - Server.

== Partition Configuration

During installation, be sure to create the logical volumes marked
optional during the partition section.

== Post-installation changes

All commands need to be run as `root`

=== Scripted changes

As many changes as possible are implemented by the `remediate` script.
The script is intended to be run after the "Third Stage Installation"
steps in the FSL10 instructions, before any further changes have been
made to the system (however initializing and adding other disks to the
RAID can intervene).

....
cd /root/fsl10
script ../remediate.txt
./remediate
exit
....

NOTE: This script should not be run more than once on a system.

=== Manual changes

This section covers manual operations after running the script.

1. Reboot and execute:
+
....
aa-enforce /etc/apparmor.d/*
....

All the CIS remediations that can applied at this point have been
completed. The next section describes some other policies that can be
considered.

=== Other polices:

This section describes other policies that may be desirable. Some
are beyond the CIS benchmark.

==== /etc/hosts.deny

Add:

....
ALL:ALL
....

==== /etc/hosts.allow

Add:

....
sshd:ALL
....

It is recommened that you further restrict `sshd` to specific hosts and/or
sub-domains.

==== Password policies

You may wish to set minimum password lengh to 12.

You may wish to set password reuse remember to 24.

==== Set remote log host and/or retention to a minimum of one year

You may wish to configure a remote log host and/or set log retention
period to at least one year.

To set a remote log host, edit the `/etc/rsyslog.conf` and
`/etc/rsyslog.d/*.conf` files and add the following line (where
`loghost.example.com` is the name of your central log host).

....
*.* @@loghost.example.com
....

Run the following command to reload the rsyslogd configuration:

....
kill -HUP rsyslogd
....

Set the retention period of system logs by editing
`/etc/logrotate.d/rsyslog`. This should be configured to store logs
for at least a minimum of a year (366 for daily 53 for weekly)..

==== Bootloader password

You may wish to create an encrypted password with grub-mkpasswd-pbkdf2:

....
grub-mkpasswd-pbkdf2
Enter password: <password>
Reenter password: <password>
Your PBKDF2 is <encrypted-password>
....

Add the following into `/etc/grub.d/00_header` or a custom
`/etc/grub.d` configuration file:

....
cat <<EOF
set superusers="<username>"
password_pbkdf2 <username> <encrypted-password>
EOF
....

If there is a requirement to be able to boot/reboot without entering
the password, edit `/etc/grub.d/10_linux` and add `--unrestricted` to the
line `CLASS=`

Example:

....
CLASS="--class gnu-linux --class gnu --class os --unrestricted"
....

Run the following commands to update the grub2 configuration and reset
the `grub.cfg` permissions:

....
update-grub
chmod go-rwx /boot/grub/grub.cfg
....

== CIS Exceptions

This section addresses the tests that failed in the CIS benchmark
after all the remediations in this document were applied.

=== 1.4.2 Ensure bootloader password is set

Must be set later by adminstrators.

=== 2.2.2 Ensure X Window System is not installed

X Window system is required for FS use.

=== 2.2.4 Ensure CUPS is not enabled

CUPS is required for operations.

=== 2.2.11 Ensure IMAP and POP3 server is not enabled

Exim4 is required as MTA; it never accepts incoming remote connections
(blocked at firewall).

=== 3.5 Firewall Configuration

The firewall is configured with `ufw` instead of `iptables` and
`ip6tables`. This causes four to six issues depending on the details
of the installation, but `ufw` provides the same security as the
recommended remediations. The configuration is set to by default deny
for incoming connections, enable incoming SSH connections, and sets
logging for all connections. Setup:

....
apt -y install ufw
ufw allow OpenSSH
ufw logging on
ufw --force enable
....

=== 4.2.1.4 Ensure rsyslog is configured to send logs to a remote log host

A remote log server must be configured by system adminstrators later.
	
=== 4.2.4 Ensure permissions on all logfiles are configured

All files except `/var/log/wtmp` have the requested permissions. That
file changes on a reboot to `rw-rw-r--`, owned by `root.wtmp`. No
sensitive information is stored in the file and making it readable for
others allows commands like `last` and `who` to work.

=== 5.2.6 Ensure SSH X11 forwarding is disabled

We require `ssh` X11 forwarding for use with FS for remote operations
and testing.

=== 5.4.2 Ensure system accounts are non-login

System accounts (i.e., accounts with user ID less than 1000) `oper`
and `prog` are needed for compatabilty with the wider VLBI community
and are only used as service accounts from AUID accounts. They require
a valid shell, but direct local login and `ssh` login (including with
keys) are disabled for these two accounts.

== CIS issues that need to be addressed

This section lists further topics related to the benchmark that should be
discussed.

=== 2.2.1.2 Ensure ntp is configured

Need FS NTP configuration. That is more secure than the benchmark since
it uses `ignore` by default.

=== 2.3.4 Ensure `telnet` client is not installed

Would prefer to keep the `telnet` client, it is useful for debugging
ASCII device protocol devices, which we have.  The security weakness
is `telnetd`, which is not installed, nor does the benchmark test
for it.

=== 4.1.1.2 Ensure system is disabled when audit logs are full

This may not be appropriate for an operational system.

=== 5.2.13 Ensure only strong ciphers are used

What ciphers should we use?

=== 5.2.14 Ensure only strong MAC algorithms are used

What MAC alogorithms should we use?

=== 5.2.15 Ensure only strong Key Exchange algorithms are used

What Key Exchange alogorithms should we use?

=== 5.2.16 Ensure SSH Idle Timeout Interval is configured

Five minutes is too short.

=== 5.3.1 Ensure password creation requirements are configured

Should we use the NASA 12 character minimum?

=== 5.4.1.4 Ensure inactive password lock is 30 days or less

This is too short for developers/troubleshooters

== CIS Remediation problems

This section details problems with the recommended remediations.

=== 2.1.2 Ensure openbsd-inetd is not installed

Remediation solves problem, but does not make the test pass. To do the
latter required 'purge'.

=== 2.2.1.2 Ensure ntp is configured

Remediation makes it less secure. A default policy of `ignore` is better.

=== 2.3.4 Ensure `telnet` client is not installed

The remediation does not make the test pass, that required 'purge'.

=== 3.2.4 Ensure suspicious packets are logged

The remediation lines added in `/etc/sysctl.d/*` are not respected at
boot (unlike all others). To overcome this, the following lines are
used in a new systemd service 'CISfix' at boot.

....
sysctl -w net.ipv4.conf.all.log_martians=1
sysctl -w net.ipv4.conf.default.log_martians=1
sysctl -w net.ipv4.route.flush=1
....

=== 4.1 Configure System Accounting (auditd)

Many of the remedations are described in terms of the contents of
`/etc/audit/audit.rules`. However, the contents of that file are
auto-generated at boot from the files in `/etc/audit/rules.d`, which
is where these remediations must go.

=== 4.1.6 Ensure events that modify the system's network environment are collected

64-bit remediation had b64 and b32 rules concatenated on one line.

=== 4.1.17 Ensure kernel module loading and unloading is collected

64-bit remediation was missing b32 rule.

