= FS Linux 10 Installation Guide
J.F.H. Quick and D.E. Horsley 
Draft Aug 2019

:sectnums:
:experimental:
:downarrow: &darr;

Please note that for each step in this guide, we recommend you carefully read all
the included caveats and notes as the material is not always logically
sequential, i.e. instructions may proceed explanations that impact what you
actually type.


== Choosing architecture and creating installation media

As of Field System version 10.0, both `i386` and `amd64` architecture are
supported natively. However, some work may be required to port your station code
from a 32-bit to a 64-bit OS. Some automatic tools have been developed for this,
and can be provided upon request.

To install Debian 9, you can either use a DVD or USB drive. The latter is
faster, and also necessary if you wish to use UEFI. Directions for creating your
installation media can be found online. 

NOTE: Don't be confused by the `amd64` name, this architecture is supports both
AMD and Intel manufactured x86-64 processors. This includes CPU lines
such as Ryzen, Epyc, Core, and Xeon. The naming scheme dates back to when Intel
had a completing and incompatible 64 bit architecture.

You can install a DVD drive, USB device or over the network. The details of
creating your installation media can be found in the Debian installation
guide available from: https://www.debian.org/releases/stretch/installmanual

Any revision of 9.x installation's should work fine, but older revisions
will want to download many security patches from the network which may
already be included in the latest revision. Note also that installing from
DVDs as described here is recommended mainly for sites with little to poor
Internet connectivity (even then use of a single DVD may suffice) and the
equivalent use of a Debian GNU/Linux 9.x "Stretch" - Official i386/amd64
"netinst" CD would suffice for installation at most sites with good
connectivity.

== Motherboard setup

// TODO: perhaps we need some general advice on setting motherboards
NOTE: This is somehting we may change before final release of FSL10. Legacy mode/BIOS emulation
might be easier, especially with disk rotations.

Modern motherboards offer two forms of booting: native UEFI or BIOS emulation ("Legacy"). There is no
particular advantage to UEFI boot other than the ability to enable secure boot, which is not supported by
Debian at the time of writing anyway. Either are supported by this installation guide, and you will be
given alternatives when the instructions.

Decide which boot mode you wan to use and select it through the motherboard setup menu (typically by
pressing kbd:[DEL] during POST.

Also make sure that the motherboard time is set to the current Universal time, ie.
UTC, and the motherboard can boot from the installation media.


== First Stage Installation

WARNING: This guide assumes that you have two disks installed in the machine
in order to set them up as a RAID pair. For RAID to work seamlessly with a
third disk later, you must make sure that the smallest disk of the three
disks available is used as the first of this initial RAID pair. Use of a
single disk (for a test install etc.) is also annotated below.

=== Insert/plug-in your installation media and reboot.

To boot of the installation media you may need to bring up your motherboards boot menu, which is typically
accessed by pressing kbd:[F12].


=== Set boot options and boot installer

At the 'Installer boot menu':

. _Highlight_ `Install` (or `Graphical install` -- only the installer
  interface differs -- but this may not work on some video hardware)
    * BIOS: press kbd:[Tab]; or
    * UEFI: kbd:[e], kbd:[{downarrow}] three times, then kbd:[End]
. To the end of the displayed command, add the additional options:

   locale=C netcfg/disable_dhcp=true time/zone=UTC

. Press:
    * BIOS: kbd:[Enter]
    * UEFI: kbd:[F10] 

// TODO: "locale=C" is begining to be a problem. Not having a UTF-8 locale set does cause
// some problems. Tmux for example is unhappy about this.

NOTE: You may omit the `netcfg/disable_dhcp=true` if you want to use DHCP to
configure the network settings of this machine, though this is not advised.

The installer will now boot.

=== Select your continent or region

Find your region from the available list and press kbd:[Enter],
then select your country, territory or area and press  kbd:[Enter] again.
(These notes were produced by selecting "North America" and then
"United States" - you may experience small differences if you select
another location)

=== Select a keyboard layout

Find your keyboard on the keymap list and press  kbd:[Enter]. (The most common one is "American English")

The installation media is now scanned and additional installer components loaded.

=== If you are presented with a dialog asking for non-free firmware files

You may need to locate the files requested (especially if they relate to
your network or disk-drive interfaces)  and place them on a USB stick which
should be inserted at this stage.  If you do have the required files select
'kbd:[Yes]', otherwise press kbd:[Tab] to select kbd:[No], then press
kbd:[Enter] to continue.

=== If you are presented with a dialog asking which interface to use 
Typically only shown if two or more network interfaces are
found, which might include a virtual firewire interface in some cases.
Select the interface you require (usually 'eth0') and press  kbd:[Enter].

====
Unless you are using DHCP (which is not advisable) you will be prompted to:
Type in the required static IP address in the form `xxx.xxx.xxx.xxx` (where
xxx is any integer from 1 - 254 inclusive) and press  kbd:[Enter].
Type in the required netmask in the form `255.yyy.yyy.yyy` (where yyy is
typically 0, 64, 128, 192 or 255) and press  kbd:[Enter].
Type in the required gateway IP address in the form `xxx.xxx.xxx.xxx` (where
xxx is any integer from 1 - 254 inclusive) and press  kbd:[Enter].
Type in the required nameserver IP addresses, space separated, in the form
`xxx.xxx.xxx.xxx` (where xxx is any integer from 1 - 254 inclusive) and
press  kbd:[Enter].

Alternatively, if you are only using the installer to initialize new disks,
you may want to use kbd:[Go Back] and directly select "Detect disks" from the
main menu to skip forward to step 10 below.
====

=== Set a hostname
Backspace over the default hostname "debian" and type in the name
you require (if not already retrieved vis DNS), then press  kbd:[Enter].
Enter the required Internet Domain name (if not found) and press  kbd:[Enter].

=== Enter a suitable root password

Twice as prompted.

=== Setup first account

Enter "Desktop User" for the name of the new user
then press  kbd:[Enter]  to accept "desktop" as the username and enter a (real)
password twice as prompted.

=== Get network time

The installer now tries to set the time using NTP
If this is not possible at your site due to your firewall etc. you may need
to press kbd:[Enter] to cancel this process.

=== Setup partitions 

NOTE: These notes assume you have disks larger than 2TB so that GPT will be the partition
format selected by the installer.

When prompted, select *Manual*

. Select first disk, something like `SCSI1 (0,0,0) (sda) - 4 TB ATA SATA HARDDISK`, and
preset kbd:[Enter]

. Installer may warn: *You have selected an entire device to partition…*. Select *Yes*

. Select the *FREE SPACE* under the first device

. Select *Create a new partition*

.  Then for
** BIOS: Enter *1MB* in the size, then select *Beginning* of the disk.
** UEFI:  Enter *1GB* in the size, then select *Beginning* of the disk.

. Then for
** BIOS: Select *Use as* then select *Reserved BIOS boot area*
** UEFI: Select *Use as* then select *EFI System Partition (ESP)*

. Now press *Done setting up the partition*.

. Next select the *FREE SPACE* and *Create a new partition* again.

. This time choose the whole amount of free space (the default).

. Select *Use as: physical volume for RAID*, then *Done setting up the partition*

. *Go to step 1 and Apply the same procedure to the second disk.*

. Select *Configure software RAID*, select *Yes* to write the changes
  to the disks.

. Select *Create MD device*, choose *RAID 1* and enter *2* as number
of devices and *0* as number of spare.

. Select the two raid partitions we just created, (these should be sda2 and sdb2)

. Select *Finish*.

. Back in partitioning, Select the space _under_ *RAID1 device #0* and press kbd:[Enter]

. Select *use as* then select *Physical volume for LVM* then *Done setting up the partition*

. Now choose the 3rd option of the partition manager *Configure the Logical Volume Manager*.

. *Create volume group* enter *vg0*, then select the raid device *md0* by pressing kbd:[Space].

. For each item in the following table run *Create logical volume*, select *vg0* as
the volume group and assign the corresonding label. Those marked with "*" are optional for non-NASA stations
+
.Logical volumes
|=======================================
| Mount point    | LV label | Size

| /              | root     | 50 GB
| /boot          | boot     | 1 GB
| swap           | swap     | 4 GB
| /tmp           | tmp      | 4 GB
| /var           | var*    | 8 GB
| /var/log       | log*    | 4 GB
| /var/log/audit | audit*  | 500 MB
| /home          | home     | 4 GB
| /usr2          | usr2     | remaining disk space *less about 50 GB*
|=======================================

. In the LVM configuration window, select *Finish*

. Then  for each logical volume in the table except swap,:
    . Select the "free space" and press kbd:[Enter]
    . Select *Use as* and press kbd:[Enter] then select *Ext4 journaling file system* 
    . Select *Mount point*, press kbd:[Enter], then select the appropriate mount point from the list or 
      use *Enter manually* if not there.
    . Select *Done setting up this partition*

. For the swap logical volume, select *Use as* then select *swap area*

. Back in the partition screen, select *Finish partitioning and write changes to
the disks*. For big disks, it may take some time to create the ext4 file
systems.


=== Configure the package manager


// TODO: too many NOTES! 

Scanning the additional DVDs (and obtaining copies of them in the
first place) is entirely optional, and is only useful if you don't have a
reliable network connection to a suitable Debian mirror and hence would
prefer not to download packages you get from the DVD.

If you start from a "netinst" CD image the installer now
assumes you will install only from the network, and jumps straight to
the "Choose your country..." part of the dialogue as detailed below.


NOTE: If you do want to use a mirror in future, it is better not to scan any
DVDs at this stage and to scan them later during Stage 2 using 'apt-cdrom'.

For each additional DVD you wish to scan, insert it in the drive, select
*Yes* and press  kbd:[Enter]  to perform the scan (which takes a while.)

(If you are using DVDs, and are prompted to insert another DVD, you
will need to use 'eject /dev/cdrom' from another virtual console to do this)

Select *No* and press  kbd:[Enter]  to continue once you are done.
If prompted, insert the Debian GNU/Linux 9.x "Stretch" - Official i386/amd64
Binary-1 DVD back into the DVD-ROM drive and press  kbd:[Enter].

WARNING: If you do scan additional DVDs, the following useful dialogue
which allows you to select a suitable network mirror from a country-based
list may be suppressed.

Select *Yes* and press  kbd:[Enter]  to use a network mirror (unless you
have inadequate Internet access - but then you must scan all DVDs.)
Choose your country from the list if available and press  kbd:[Enter].
(If your country is not available choose the country nearest to you in a
network connectivity sense.)

Select the fastest Debian mirror from those available.

TIP: The new `deb.debian.org` mirror is a good choice for most
sites as it uses DNS to find a local mirror.

Enter any necessary HTTP: proxy information (usually left blank.)

=== Do not participate in popularity-contest

When prompted to join the popularity-contest,
select *No* and press kbd:[Enter]  

=== Choose your packages

When prompted to choose packages, 
select *SSH server* By pressing kbd:[Space] on it (unless you don't want it).  

TIP: If you have a small disks and are worried about space, then you can
also press kbd:[Space] on "Desktop Environment" to unselect it (which may
then change the dialogue presented below).

Finally press kbd:[Tab] to select *Continue* and then
kbd:[Enter] to install the standard system.

The Debian standard system is now installed from the installation media plus any
updates from the network mirror and/or security.debian.org site if they can be
reached. 

This can take a while, up to one and half hours or more.

=== Install the GRUB bootloader

// FIXME: need a comment about UEFI here

. At *Install GRUB to Master Boot Record* select *yes* then select */dev/sda*
** UEFI: you will not be presented with this option; GRUB will automatically be
   installed

When prompted, press kbd:[Enter] to install to the master boot record of the
primary disk.


=== Remove installation media 
The DVD from the DVD-ROM drive (it should be auto-ejected), or unplug the
USB drive and press  kbd:[Enter]  to reboot into the newly installed system.

TIP: It would generally be wise to disable booting from DVD-ROM and floppy ie. 
anything other than the hard drive, in the BIOS just in case someone
leaves something nasty in the machine's removable drives by mistake.


== Second Stage Installation:

You can now boot to your new OS.

=== Login as root 

Switch to Virtual Console 3, by pressing kbd:[Ctrl+Alt+F3].

Enter `root` and press kbd:[Enter], then enter the root password you set
earlier.

NOTE: Previous versions of Debian ran X11 on virtual console 7. As of
Debian 9, the desktop environment consoles are virtual console 1 and 2. 

TIP: If the login screen is painfully slow, try disabling Wayland in
GDM3. Edit `/etc/gdm3/daemon.conf` and uncomment the line `WaylandEnable=false`

=== Remove the dummy "Desktop User" (optional)

Unless you want another account that that is set up to use the default
desktop environment, delete "desktop" with:

   deluser --remove-home desktop

NOTE: If you do keep this account, you will not be able to run the FS from
it unless you add this account into the additional hardware access groups
such as is done for oper/prog by FSADAPT.

=== Setup HTTP Proxy for APT (Optional)
Should you wish to make APT use an HTTP proxy for downloads,
create the new file `/etc/apt/apt.conf.d/00proxies` using `vi` containing:

   ACQUIRE::http::Proxy "http://proxy.some.where:8080/"; 

to use a proxy `proxy.some.where` at port 8080 for example.

=== Edit /etc/apt/sources.list 

Using your favourite text editor, eg `vi`, and comment out all 'cdrom' entries
(unless you don't have a decent Internet connection and need to use DVDs,
whereupon the dialogue presented below may differ) and check you have the
equivalent of the following entries towards the top of the file, adding
in 'contrib' and/or 'non-free' as needed:

   deb http://deb.debian.org/debian/ stretch main contrib non-free
   deb-src http://deb.debian.org/debian/ stretch main contrib non-free

and likewise the equivalent of the following entries towards the bottom of
the file, again adding in 'contrib' and/or non-free as needed:

   deb http://deb.debian.org/debian/ stretch-updates main contrib non-free
   deb-src http://deb.debian.org/debian/ stretch-updates main contrib non-free

(where you can use any suitable mirror instead of "ftp.us.debian.org")

Also add `contrib` and/or `non-free` to the lines referring to the
security.debian.org mirror in the middle of the file.

IMPORTANT: you _MUST_ use "stretch" and _NOT_ "stable" for the distribution in
all these entries (but CD/DVD entries might use "unstable".)

=== Next tell APT to update its internal source list of packages using

TIP: Recent versions of Debian have the `apt` program, which gives a more
     user-friendly interface to the package manager than `apt-get`

   apt update 

NOTE: It is also possible to add additional DVDs at this stage using the
'apt-cdrom add' command 

=== Install the latest Linux kernel and matching headers for your architecture

// TODO: is this needed anymore?

Run 'cat /proc/version' to see what flavour you require.

then run

   apt install linux-image-686-pae linux-headers-686-pae

(on Intel Pentium Pro/II/III/4M/D, Xeon, Core of Atom and AMD GeodeNX,
Athlon (K7), Duron, Opteron, Sempron, Turion or Phenon 32-bit processors,)
   
_OR_

   apt install linux-image-amd64 linux-headers-amd64

(on AMD64 or Intel EM64T 64-bit processors, also known as x86_64.)

pressing kbd:[Enter] to confirm the installation of +- 12 new packages.

NOTE: that if you are using DVDs, and are prompted to insert another DVD, you
may need to use 'eject /dev/cdrom' from another virtual console to do this)

=== Download the FS Linux 10 "dpkg" package selections

As follows:

// TODO: this needs to be updated

    ftp ftp.hartrao.ac.za
    user: ftp
    password: your@email.address
    cd /pub/fs9x
    get fsl9.selections
    quit

=== Feed the package selections into "dpkg"

using the commands

   apt install dselect
   dselect update
   dpkg --set-selections < fsl10.selections


=== Start the additional package installation

Run using the command

   apt-get dselect-upgrade

then pressing kbd:[Enter] to confirm any updating of installed packages (where
you have an Internet connection) and the installation of +-105 new packages
(unless you did not select the Desktop or added other tasks earlier -
currently downloading at least 95MB from the Internet and/or DVDs).

Downloading commences for up to half an hour (depending on your Internet
access and the exact revision of DVDs used):
   
Installation runs to completion.

=== Wait for the RAID1 disk mirroring to set up

Watch its progress with:

   cat /proc/mdstat

until none of the three arrays shows a recovery in progress.  This can take
a significant amount of time, particularly with large disks.  For example
my 80GB test disks took over half an hour.

Technically, you only have to wait for the /dev/md0 RAID to complete its
recovery before proceeding to the next step, the other two RAIDs only need
to complete their recovery before you reboot in stage 3 below.

=== Install "GRUB" secondary disk (if available)

// TODO: this needs to mention UEFI grub too.

Install GRUB to the Master Boot Record by running:

   dpkg-reconfigure -plow grub-pc

and after pressing kbd:[Enter] twice to accept the kernel command line extra
arguments and default command line argruments, use the arrow keys and
kbd:[Space] to select both /dev/sda and /dev/sdb (but not /dev/md0) and
press kbd:[Enter] to finalise the reconfiguration.
(You should then see "Installation finished. No error reported" appear
twice in the progress messages as GRUB is re-installed to both drives.)

=== Clean up the APT download directory
// TODO: perhaps we can change to `apt-listchanges`

So that the update mechanism will work correctly, run

   apt-get clean


== Third Stage Installation (FSADAPT):

=== Download the latest available FSADAPT 9.0.x tarball
(it is not related in any way to the FS version you want to install):

Eg:

   ftp ftp.hartrao.ac.za kbd:[CR]
   user: ftp kbd:[CR]
   password: kbd:[ your@email.address ] kbd:[CR]
         cd /pub/fs9x kbd:[CR]
   get fsadapt-9.0.x.tgz kbd:[CR]
   quit kbd:[CR]

=== Unpack the FSADAPT 9.0.x tarball

using the command

   tar xzf fsadapt-9.0.x.tgz

=== Start up the FSADAPT script

as follows:

    cd fsadapt
    ./fsadapt

=== FS Adaptation: Modifications (Window 1)

All of the steps shown in Window 1 are
required and should already be pre-selected apart from "noident", "ftpdlog"
and "govt" which are optional.  After selecting any additional optional
step required, simply press kbd:[Enter] with *OK* selected to continue.

=== FS Adaptation: Setup (Window 2)

All of the steps in Window 2 need to be done once
with the exception of "sshkeys" which can be used to recover old SSH keys
from a backup.  So simply press kbd:[Enter] with the *OK* selected to
continue.

NOTE: The "updates" option relies on email to 'root' being re-directed to some
      mailbox that will be read regularly, so make sure you set that up and
      test it as well.  The installer sets it up to go the 'desktop' account
      by default which would definitely be a problem if you have removed that!

=== GPIB driver configuration

On the "/etc/gpib.conf" screen, use the up/down
arrow keys to select the required GPIB controller and press kbd:[Enter] on
*OK* to continue.

=== Serial port configuration

On the "/etc/default/grub: serial port configuration" screen
up/down arrow keys to select the required RS232 serial card and press
kbd:[Enter] on *OK* to continue.

=== FS Adaptation: Settings (Window 3)

On Window 3 modify the email settings as required.  Simply press kbd:[Enter] on
*OK* to continue.

=== FS Adaptation: Network Services (Window 4) 

The Window 4 will show what services are enabled.  Use the up/down arrows
and kbd:[Space] to select "secure" and press kbd:[Enter] on *OK*.  Thereafter
use the up/down arrows and kbd:[Space] to select those services you actually
need and press kbd:[Enter] on *OK* to set them up and finish with
FSADAPT.  (This will complain about the current start and stop runlevels of
the avahi-daemon if you have disabled it as recommended for a secure
system.) 

Note that the FSADAPT script can be re-run at a later date should you need to
change the adaptations.

=== Now set proper passwords for the 'oper' and 'prog' accounts:

   passwd oper
   passwd prog

entering the passwords twice as prompted.


=== Place a copy of the latest fs-9.11.x archive in your "/tmp" directory

where 'x' denotes the latest patch number (>=9.13.?) in the following.

=== Extract the FS source from the archive

   cd /
   tar xzpf /tmp/fs-9.11.x.tgz

=== Install default copies of all the FS related directories

   cd /usr2/fs-9.11.x
   make install

and enter 'y' to confirm installation.

=== Make the FS

IMPORTANT: Log-out of the console as root, and log-in again as prog.

   cd /usr2/fs
   make >& /dev/null

then

  make

to confirm that everything compiled correctly.

=== Wait for the RAID1 disk mirroring to set up, watching its progress with:

   cat /proc/mdstat

until none of the three arrays shows a recovery in progress.

NOTE: Sometimes the RAID system gets stuck and using 'cat /proc/mdstat' does
      not show any active re-syncs but only a RAID set with "resync=PENDING".
      In this case, you will need to re-trigger the RAID set up process as root
      by 'failing' the secondary disk partition in the appropriate RAID pair,
      'removing' it and 'adding' it back as shown in the following example:
      +
         mdadm /dev/md1 -f /dev/sdb3
         mdadm /dev/md1 -r /dev/sdb3
         mdadm /dev/md1 -a /dev/sdb3
      +
      until 'cat /proc/mdstat' shows that all the RAIDs are successfully set up.

The final step is to remove any DVD from the machine and to restart the machine
using "reboot" as root or kbd:[Ctrl+Alt+Del] whilst watching that everything
starts up smoothly.

Your new FS machine should now be ready to be customised to your requirements
by tailoring the control files in `/usr2/control` and adding suitable station
specific software to `/usr2/st`.  See the files in the `/usr2/fs/misc` directory
for more information.

== Post install hardening

For NASA stations or those who wish to conform to the CIS recommendations, now move on
to the <<fsl10-cis.adoc#,CIS hardening FSL10>> document.
