= CIS recommended partitions for FSL10
David E Horsley
Jan 2019

Run usual installation, then at the partition screen. Select ``Manual''.

Select first disk, eg. something like

....
SCSI1 (0,0,0) (sda) - 4 TB ATA SATA HARDDISK
....

Installer may warn: ``You have selected an entire device to
partition…''. Select ``Yes''

Select the ``FREE SPACE'' under the first device

Select ``Create a new partition''

Enter ``1MB'' in the size, then select ``Beginning'' of the disk.

Select ``Use as'' then select ``Reserved BIOS boot area''

Then ``Done setting up the partition''.

Next select the ``FREE SPACE'' and ``Create a new partition'' again.

This time choose the whole amount of free space (the default).

Select ``Use as: physical volume for RAID'', then ``Done setting up the
partition''

Apply the same to the second disk.

Select ``Configure software RAID'', select ``Yes'' to write the changes
to the disks.

Select ``Create MD device'', choose ``RAID 1'' and enter ``2'' as number
of devices and ``0'' as number of spare.

Select the two raid partitions we just created, should be sda2 and sdb2)

Select ``Finish''.

Back in partitioning Select the free space under ``RAID device #0''

Select ``use as'' then select ``Physical volume for LVM'' then ``Done
setting up the partition''

Now choose the 3rd option of the partition manager ``Configure the
Logical Volume Manager''.

``Create volume group'' enter ``vg0'' select the raid device ``md0''.

For each of the following run ``Create logical volume'', select ``vg0''
and

[cols="<,<,<",options="header",]
|=======================================
|Mount point |LV label |Size
|/ |root |50 GB
|/boot |boot |1 GB
|swap |swap |4 GB
|/tmp |tmp |4 GB
|/var |var |8 GB
|/var/log |log |4 GB
|/var/log/audit |audit |500 MB
|/home |home |4 GB
|/usr2 |usr2 |remaining space less 50 GB
|=======================================

Free space in VG can be used for snapshots or if you need to resize one
of the other partitions.

Then for each, except ``swap'', select the free space and select ``Use
as ext4'' and select the mount point as appropriate.

Select finish and write changes to the disks. For big disks, it may take
some time to create the ext4 file systems.

At ``Install GRUB to Master Boot Record'' select ``yes'' then select
``/dev/sda''

After installation install Grub to the second device with Post install:

....
grub-install /dev/sdb
....

== Notes

Grub /boot on raid+lvm:

https://unix.stackexchange.com/questions/390219/does-grub2-support-boot-on-lvm-on-md-raid

For testing GPT in VirtualBox, you will need to create a large disk
image. Use:

....
vboxmanage createhd --filename 3TB.vdi --size 3000000 --format VDI --variant Standard
....
