#!/bin/sh
#mdstat for FSL7 and later
cat /proc/mdstat
echo
echo 'Disk       Serial Number'
for disk in $(ls /dev/sd?); do
	if [ -b $disk ]; then
		echo "$disk  " $(lsblk --nodeps -no serial $disk)
	fi
done
