#!/bin/bash
#
# Copyright (c) 2020 NVI, Inc.
#
# This file is part of FSL10 Linux distribution.
# (see http://github.com/nvi-inc/fsl10).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

set -e
if echo $DISPLAY |grep -q localhost; then
  sudo -u prog XCOOKIE="$(xauth list $DISPLAY)" -i "$@"
else
  if ! [ -z $DISPLAY ]; then
    if ! xhost|grep -q 'SI:localuser:prog'; then
      xhost +SI:localuser:prog >/dev/null
    fi
    sudo -u prog -i "$@"
  else 
    sudo -u prog -i "$@"
  fi
fi
