#!/bin/bash
set -e
if echo $DISPLAY |grep -q localhost; then
  sudo -u prog XCOOKIE="$(xauth list $DISPLAY)" -i "$@"
else
  if ! [ -z $DISPLAY ]; then
    if ! xhost|grep -q 'SI:localuser:prog'; then
      xhost +SI:localuser:prog >/dev/null
    fi
    sudo -u prog -i "$@"
  else 
    sudo -u prog -i "$@"
  fi
fi
