#!/bin/bash
set -e
if echo $DISPLAY |grep -q localhost; then
  sudo -u root XCOOKIE="$(xauth list $DISPLAY)" -i "$@"
else
  if ! [ -z $DISPLAY ]; then
    if ! xhost|grep -q 'SI:localuser:root'; then
      xhost +SI:localuser:root >/dev/null
    fi
    sudo -u root -i "$@"
  else 
    sudo -u root -i "$@"
  fi
fi
